version: '2.2'
services:
  ktm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ktm-rest
    container_name: ktm-rest.dev
    ports:
      - 8080:8080
    networks:
      - network1

networks:
  network1: